import pandas as pd
import matplotlib.pyplot as plt


def plot_results():
    try:
        # 1. Read the CSV generated by Java
        data = pd.read_csv("tutor_results.csv")

        # 2. Setup the plot
        plt.figure(figsize=(10, 6))
        plt.plot(
            data["NumGroups"],
            data["TimeMillis"],
            marker="o",
            linestyle="-",
            color="#1f77b4",
            linewidth=2,
            label="Edmonds-Karp (Java)",
        )

        # 3. Styling
        plt.title("Performance Analysis: Tutor Allocation (Max-Flow)", fontsize=14)
        plt.xlabel("Number of Student Groups (Problem Size)", fontsize=12)
        plt.ylabel("Execution Time (ms)", fontsize=12)
        plt.grid(True, linestyle="--", alpha=0.7)
        plt.legend()

        # 4. Save
        output_file = "tutor_runtime_java.png"
        plt.savefig(output_file, dpi=300)
        print(f"Graph successfully saved as {output_file}")

    except FileNotFoundError:
        print("Error: 'tutor_results.csv' not found.")
        print("Make sure to run the Java 'TutorAllocation' class first!")


if __name__ == "__main__":
    plot_results()
